
***NOTE: Messages are organized per MPI process in separate sections below.


**********************************
*  Message file output, cpu #1   *
**********************************

-------------------------------------------------------------------------------

  INFORMATION REGARDING INITIAL CONTACT OVERCLOSURES FOR NEWLY DEFINED GENERAL
  CONTACT INTERACTIONS IN STEP 1

-------------------------------------------------------------------------------

  Adjacent slave nodes 179 and 180 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 420 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 179 and 199 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 420 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 198 and 199 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 414 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 198 and 218 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 414 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 217 and 218 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 402 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 217 and 237 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 402 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 236 and 237 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 396 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 236 and 256 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 396 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 255 and 256 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 384 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 255 and 275 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 384 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 274 and 275 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 378 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 274 and 294 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 378 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 293 and 294 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 372 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 293 and 313 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 372 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 312 and 313 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 360 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 312 and 332 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 360 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 331 and 332 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 354 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 331 and 351 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 354 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 350 and 351 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 342 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 350 and 370 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 342 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 369 and 370 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 336 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 369 and 389 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 336 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 388 and 389 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 330 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 179 and 180 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 420 of instance STRIP in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 179 and 199 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 420 of instance STRIP in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 198 and 199 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 414 of instance STRIP in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 198 and 218 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 414 of instance STRIP in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 217 and 218 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 402 of instance STRIP in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 217 and 237 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 402 of instance STRIP in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 236 and 237 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 396 of instance STRIP in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 236 and 256 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 396 of instance STRIP in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 255 and 256 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 384 of instance STRIP in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 255 and 275 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 384 of instance STRIP in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 274 and 275 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 378 of instance STRIP in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 274 and 294 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 378 of instance STRIP in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 293 and 294 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 372 of instance STRIP in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 293 and 313 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 372 of instance STRIP in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 312 and 313 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 360 of instance STRIP in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 312 and 332 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 360 of instance STRIP in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 331 and 332 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 354 of instance STRIP in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 331 and 351 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 354 of instance STRIP in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 350 and 351 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 342 of instance STRIP in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 350 and 370 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 342 of instance STRIP in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 369 and 370 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 336 of instance STRIP in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 369 and 389 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 336 of instance STRIP in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 388 and 389 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 330 of instance STRIP in the
  configuration after the initial overclosure procedure.


***WARNING: The option *BOUNDARY,TYPE=DISPLACEMENT has been used with a jump
            of 100.0000E-03  at DOF 1 of node TRANSLATE.9 at the beginning of
            step 2.


***WARNING: The option *BOUNDARY,TYPE=DISPLACEMENT has been used with a jump
            of 52.1150E-03  at DOF 1 of node TRANSLATE.9 at the beginning of
            step 3.


***WARNING: The option *BOUNDARY,TYPE=DISPLACEMENT has been used with a jump
            of 11.9845      at DOF 2 of node TRANSLATE.9 at the beginning of
            step 3.


**********************************
*  Message file output, cpu #2   *
**********************************

-------------------------------------------------------------------------------

  INFORMATION REGARDING INITIAL CONTACT OVERCLOSURES FOR NEWLY DEFINED GENERAL
  CONTACT INTERACTIONS IN STEP 1

-------------------------------------------------------------------------------

**********************************
*  Message file output, cpu #3   *
**********************************

-------------------------------------------------------------------------------

  INFORMATION REGARDING INITIAL CONTACT OVERCLOSURES FOR NEWLY DEFINED GENERAL
  CONTACT INTERACTIONS IN STEP 1

-------------------------------------------------------------------------------

  Adjacent slave nodes 1 and 129 of instance MOULD may be on opposite sides of
  a surface near face S1 of element 847 of instance STRIP in the configuration
  before the initial overclosure procedure.


  Adjacent slave nodes 1 and 129 of instance MOULD may be on opposite sides of
  a surface near face S1 of element 847 of instance STRIP in the configuration
  before the initial overclosure procedure.


  Adjacent slave nodes 122 and 176 of instance MOULD may be on opposite sides
  of a surface near face S6 of element 415 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 122 and 195 of instance MOULD may be on the same side
  of a surface near face S6 of element 415 of instance STRIP but still crossed
  the surface in the configuration before the initial overclosure procedure.


  Adjacent slave nodes 121 and 195 of instance MOULD may be on opposite sides
  of a surface near face S6 of element 409 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 121 and 214 of instance MOULD may be on the same side
  of a surface near face S6 of element 409 of instance STRIP but still crossed
  the surface in the configuration before the initial overclosure procedure.


  Adjacent slave nodes 120 and 214 of instance MOULD may be on opposite sides
  of a surface near face S6 of element 397 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 120 and 233 of instance MOULD may be on the same side
  of a surface near face S6 of element 397 of instance STRIP but still crossed
  the surface in the configuration before the initial overclosure procedure.


  Adjacent slave nodes 119 and 233 of instance MOULD may be on opposite sides
  of a surface near face S6 of element 391 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 119 and 252 of instance MOULD may be on the same side
  of a surface near face S6 of element 391 of instance STRIP but still crossed
  the surface in the configuration before the initial overclosure procedure.


  Adjacent slave nodes 118 and 252 of instance MOULD may be on the same side
  of a surface near face S6 of element 385 of instance STRIP but still crossed
  the surface in the configuration before the initial overclosure procedure.


  Adjacent slave nodes 118 and 271 of instance MOULD may be on the same side
  of a surface near face S6 of element 379 of instance STRIP but still crossed
  the surface in the configuration before the initial overclosure procedure.


  Adjacent slave nodes 117 and 271 of instance MOULD may be on opposite sides
  of a surface near face S6 of element 373 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 1 and 129 of instance MOULD may be on opposite sides of
  a surface near face S1 of element 847 of instance STRIP in the configuration
  after the initial overclosure procedure.


  Adjacent slave nodes 1 and 129 of instance MOULD may be on opposite sides of
  a surface near face S1 of element 847 of instance STRIP in the configuration
  after the initial overclosure procedure.


  Adjacent slave nodes 122 and 176 of instance MOULD may be on opposite sides
  of a surface near face S6 of element 415 of instance STRIP in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 122 and 195 of instance MOULD may be on the same side
  of a surface near face S6 of element 415 of instance STRIP but still crossed
  the surface in the configuration after the initial overclosure procedure.


  Adjacent slave nodes 121 and 195 of instance MOULD may be on opposite sides
  of a surface near face S6 of element 409 of instance STRIP in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 121 and 214 of instance MOULD may be on the same side
  of a surface near face S6 of element 409 of instance STRIP but still crossed
  the surface in the configuration after the initial overclosure procedure.


  Adjacent slave nodes 120 and 214 of instance MOULD may be on opposite sides
  of a surface near face S6 of element 397 of instance STRIP in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 120 and 233 of instance MOULD may be on the same side
  of a surface near face S6 of element 397 of instance STRIP but still crossed
  the surface in the configuration after the initial overclosure procedure.


  Adjacent slave nodes 119 and 233 of instance MOULD may be on opposite sides
  of a surface near face S6 of element 391 of instance STRIP in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 119 and 252 of instance MOULD may be on the same side
  of a surface near face S6 of element 391 of instance STRIP but still crossed
  the surface in the configuration after the initial overclosure procedure.


  Adjacent slave nodes 118 and 252 of instance MOULD may be on the same side
  of a surface near face S6 of element 385 of instance STRIP but still crossed
  the surface in the configuration after the initial overclosure procedure.


  Adjacent slave nodes 118 and 271 of instance MOULD may be on the same side
  of a surface near face S6 of element 379 of instance STRIP but still crossed
  the surface in the configuration after the initial overclosure procedure.


  Adjacent slave nodes 117 and 271 of instance MOULD may be on opposite sides
  of a surface near face S6 of element 373 of instance STRIP in the
  configuration after the initial overclosure procedure.


**********************************
*  Message file output, cpu #4   *
**********************************

-------------------------------------------------------------------------------

  INFORMATION REGARDING INITIAL CONTACT OVERCLOSURES FOR NEWLY DEFINED GENERAL
  CONTACT INTERACTIONS IN STEP 1

-------------------------------------------------------------------------------

  Adjacent slave nodes 116 and 290 of instance MOULD may be on opposite sides
  of a surface near face S6 of element 367 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 116 and 309 of instance MOULD may be on the same side
  of a surface near face S6 of element 367 of instance STRIP but still crossed
  the surface in the configuration before the initial overclosure procedure.


  Adjacent slave nodes 115 and 309 of instance MOULD may be on opposite sides
  of a surface near face S6 of element 355 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 115 and 328 of instance MOULD may be on the same side
  of a surface near face S6 of element 355 of instance STRIP but still crossed
  the surface in the configuration before the initial overclosure procedure.


  Adjacent slave nodes 114 and 328 of instance MOULD may be on opposite sides
  of a surface near face S6 of element 349 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 114 and 347 of instance MOULD may be on the same side
  of a surface near face S6 of element 349 of instance STRIP but still crossed
  the surface in the configuration before the initial overclosure procedure.


  Adjacent slave nodes 113 and 347 of instance MOULD may be on the same side
  of a surface near face S6 of element 343 of instance STRIP but still crossed
  the surface in the configuration before the initial overclosure procedure.


  Adjacent slave nodes 113 and 366 of instance MOULD may be on the same side
  of a surface near face S6 of element 337 of instance STRIP but still crossed
  the surface in the configuration before the initial overclosure procedure.


  Adjacent slave nodes 112 and 366 of instance MOULD may be on opposite sides
  of a surface near face S6 of element 331 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 112 and 385 of instance MOULD may be on the same side
  of a surface near face S6 of element 331 of instance STRIP but still crossed
  the surface in the configuration before the initial overclosure procedure.


  Adjacent slave nodes 111 and 385 of instance MOULD may be on opposite sides
  of a surface near face S6 of element 325 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 116 and 290 of instance MOULD may be on opposite sides
  of a surface near face S6 of element 367 of instance STRIP in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 116 and 309 of instance MOULD may be on the same side
  of a surface near face S6 of element 367 of instance STRIP but still crossed
  the surface in the configuration after the initial overclosure procedure.


  Adjacent slave nodes 115 and 309 of instance MOULD may be on opposite sides
  of a surface near face S6 of element 355 of instance STRIP in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 115 and 328 of instance MOULD may be on the same side
  of a surface near face S6 of element 355 of instance STRIP but still crossed
  the surface in the configuration after the initial overclosure procedure.


  Adjacent slave nodes 114 and 328 of instance MOULD may be on opposite sides
  of a surface near face S6 of element 349 of instance STRIP in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 114 and 347 of instance MOULD may be on the same side
  of a surface near face S6 of element 349 of instance STRIP but still crossed
  the surface in the configuration after the initial overclosure procedure.


  Adjacent slave nodes 113 and 347 of instance MOULD may be on the same side
  of a surface near face S6 of element 343 of instance STRIP but still crossed
  the surface in the configuration after the initial overclosure procedure.


  Adjacent slave nodes 113 and 366 of instance MOULD may be on the same side
  of a surface near face S6 of element 337 of instance STRIP but still crossed
  the surface in the configuration after the initial overclosure procedure.


  Adjacent slave nodes 112 and 366 of instance MOULD may be on opposite sides
  of a surface near face S6 of element 331 of instance STRIP in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 112 and 385 of instance MOULD may be on the same side
  of a surface near face S6 of element 331 of instance STRIP but still crossed
  the surface in the configuration after the initial overclosure procedure.


  Adjacent slave nodes 111 and 385 of instance MOULD may be on opposite sides
  of a surface near face S6 of element 325 of instance STRIP in the
  configuration after the initial overclosure procedure.


**********************************
*  Message file output, cpu #5   *
**********************************

-------------------------------------------------------------------------------

  INFORMATION REGARDING INITIAL CONTACT OVERCLOSURES FOR NEWLY DEFINED GENERAL
  CONTACT INTERACTIONS IN STEP 1

-------------------------------------------------------------------------------

  Adjacent slave nodes 407 and 408 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 318 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 407 and 427 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 318 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 426 and 427 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 312 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 426 and 446 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 312 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 464 and 465 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 294 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 464 and 484 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 294 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 445 and 446 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 300 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 445 and 465 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 300 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 483 and 484 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 288 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 483 and 503 of instance MOULD may be on the same side
  of a surface near face S4 of element 282 of instance STRIP but still crossed
  the surface in the configuration before the initial overclosure procedure.


  Adjacent slave nodes 502 and 503 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 276 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 502 and 522 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 276 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 521 and 522 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 270 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 521 and 541 of instance MOULD may be on the same side
  of a surface near face S4 of element 264 of instance STRIP but still crossed
  the surface in the configuration before the initial overclosure procedure.


  Adjacent slave nodes 540 and 541 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 258 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 540 and 560 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 258 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 559 and 560 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 252 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 559 and 579 of instance MOULD may be on the same side
  of a surface near face S4 of element 246 of instance STRIP but still crossed
  the surface in the configuration before the initial overclosure procedure.


  Adjacent slave nodes 578 and 579 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 246 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 578 and 598 of instance MOULD may be on the same side
  of a surface near face S4 of element 240 of instance STRIP but still crossed
  the surface in the configuration before the initial overclosure procedure.


  Adjacent slave nodes 597 and 598 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 234 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 597 and 617 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 234 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 616 and 617 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 228 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 407 and 408 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 318 of instance STRIP in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 407 and 427 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 318 of instance STRIP in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 426 and 427 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 312 of instance STRIP in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 426 and 446 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 312 of instance STRIP in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 464 and 465 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 294 of instance STRIP in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 464 and 484 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 294 of instance STRIP in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 445 and 446 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 300 of instance STRIP in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 445 and 465 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 300 of instance STRIP in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 483 and 484 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 288 of instance STRIP in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 483 and 503 of instance MOULD may be on the same side
  of a surface near face S4 of element 282 of instance STRIP but still crossed
  the surface in the configuration after the initial overclosure procedure.


  Adjacent slave nodes 502 and 503 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 276 of instance STRIP in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 502 and 522 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 276 of instance STRIP in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 521 and 522 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 270 of instance STRIP in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 521 and 541 of instance MOULD may be on the same side
  of a surface near face S4 of element 264 of instance STRIP but still crossed
  the surface in the configuration after the initial overclosure procedure.


  Adjacent slave nodes 540 and 541 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 258 of instance STRIP in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 540 and 560 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 258 of instance STRIP in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 559 and 560 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 252 of instance STRIP in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 559 and 579 of instance MOULD may be on the same side
  of a surface near face S4 of element 246 of instance STRIP but still crossed
  the surface in the configuration after the initial overclosure procedure.


  Adjacent slave nodes 578 and 579 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 246 of instance STRIP in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 578 and 598 of instance MOULD may be on the same side
  of a surface near face S4 of element 240 of instance STRIP but still crossed
  the surface in the configuration after the initial overclosure procedure.


  Adjacent slave nodes 597 and 598 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 234 of instance STRIP in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 597 and 617 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 234 of instance STRIP in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 616 and 617 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 228 of instance STRIP in the
  configuration after the initial overclosure procedure.


**********************************
*  Message file output, cpu #6   *
**********************************

-------------------------------------------------------------------------------

  INFORMATION REGARDING INITIAL CONTACT OVERCLOSURES FOR NEWLY DEFINED GENERAL
  CONTACT INTERACTIONS IN STEP 1

-------------------------------------------------------------------------------

**********************************
*  Message file output, cpu #7   *
**********************************

-------------------------------------------------------------------------------

  INFORMATION REGARDING INITIAL CONTACT OVERCLOSURES FOR NEWLY DEFINED GENERAL
  CONTACT INTERACTIONS IN STEP 1

-------------------------------------------------------------------------------

  Adjacent slave nodes 109 and 423 of instance MOULD may be on opposite sides
  of a surface near face S6 of element 307 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 109 and 442 of instance MOULD may be on the same side
  of a surface near face S6 of element 307 of instance STRIP but still crossed
  the surface in the configuration before the initial overclosure procedure.


  Adjacent slave nodes 108 and 442 of instance MOULD may be on opposite sides
  of a surface near face S6 of element 295 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 108 and 461 of instance MOULD may be on the same side
  of a surface near face S6 of element 295 of instance STRIP but still crossed
  the surface in the configuration before the initial overclosure procedure.


  Adjacent slave nodes 107 and 461 of instance MOULD may be on opposite sides
  of a surface near face S6 of element 289 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 107 and 480 of instance MOULD may be on the same side
  of a surface near face S6 of element 289 of instance STRIP but still crossed
  the surface in the configuration before the initial overclosure procedure.


  Adjacent slave nodes 106 and 480 of instance MOULD may be on opposite sides
  of a surface near face S6 of element 283 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 106 and 499 of instance MOULD may be on the same side
  of a surface near face S6 of element 277 of instance STRIP but still crossed
  the surface in the configuration before the initial overclosure procedure.


  Adjacent slave nodes 105 and 499 of instance MOULD may be on opposite sides
  of a surface near face S6 of element 271 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 109 and 423 of instance MOULD may be on opposite sides
  of a surface near face S6 of element 307 of instance STRIP in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 109 and 442 of instance MOULD may be on the same side
  of a surface near face S6 of element 307 of instance STRIP but still crossed
  the surface in the configuration after the initial overclosure procedure.


  Adjacent slave nodes 108 and 442 of instance MOULD may be on opposite sides
  of a surface near face S6 of element 295 of instance STRIP in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 108 and 461 of instance MOULD may be on the same side
  of a surface near face S6 of element 295 of instance STRIP but still crossed
  the surface in the configuration after the initial overclosure procedure.


  Adjacent slave nodes 107 and 461 of instance MOULD may be on opposite sides
  of a surface near face S6 of element 289 of instance STRIP in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 107 and 480 of instance MOULD may be on the same side
  of a surface near face S6 of element 289 of instance STRIP but still crossed
  the surface in the configuration after the initial overclosure procedure.


  Adjacent slave nodes 106 and 480 of instance MOULD may be on opposite sides
  of a surface near face S6 of element 283 of instance STRIP in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 106 and 499 of instance MOULD may be on the same side
  of a surface near face S6 of element 277 of instance STRIP but still crossed
  the surface in the configuration after the initial overclosure procedure.


  Adjacent slave nodes 105 and 499 of instance MOULD may be on opposite sides
  of a surface near face S6 of element 271 of instance STRIP in the
  configuration after the initial overclosure procedure.


**********************************
*  Message file output, cpu #8   *
**********************************

-------------------------------------------------------------------------------

  INFORMATION REGARDING INITIAL CONTACT OVERCLOSURES FOR NEWLY DEFINED GENERAL
  CONTACT INTERACTIONS IN STEP 1

-------------------------------------------------------------------------------

  Adjacent slave nodes 103 and 537 of instance MOULD may be on opposite sides
  of a surface near face S6 of element 253 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 103 and 556 of instance MOULD may be on the same side
  of a surface near face S6 of element 253 of instance STRIP but still crossed
  the surface in the configuration before the initial overclosure procedure.


  Adjacent slave nodes 102 and 556 of instance MOULD may be on opposite sides
  of a surface near face S6 of element 247 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 102 and 575 of instance MOULD may be on the same side
  of a surface near face S6 of element 247 of instance STRIP but still crossed
  the surface in the configuration before the initial overclosure procedure.


  Adjacent slave nodes 101 and 575 of instance MOULD may be on opposite sides
  of a surface near face S6 of element 241 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 101 and 594 of instance MOULD may be on the same side
  of a surface near face S6 of element 235 of instance STRIP but still crossed
  the surface in the configuration before the initial overclosure procedure.


  Adjacent slave nodes 100 and 594 of instance MOULD may be on opposite sides
  of a surface near face S6 of element 229 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 100 and 613 of instance MOULD may be on the same side
  of a surface near face S6 of element 229 of instance STRIP but still crossed
  the surface in the configuration before the initial overclosure procedure.


  Adjacent slave nodes 99 and 613 of instance MOULD may be on opposite sides
  of a surface near face S6 of element 223 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 99 and 632 of instance MOULD may be on the same side of
  a surface near face S6 of element 217 of instance STRIP but still crossed
  the surface in the configuration before the initial overclosure procedure.


  Adjacent slave nodes 98 and 632 of instance MOULD may be on opposite sides
  of a surface near face S6 of element 211 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 103 and 537 of instance MOULD may be on opposite sides
  of a surface near face S6 of element 253 of instance STRIP in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 103 and 556 of instance MOULD may be on the same side
  of a surface near face S6 of element 253 of instance STRIP but still crossed
  the surface in the configuration after the initial overclosure procedure.


  Adjacent slave nodes 102 and 556 of instance MOULD may be on opposite sides
  of a surface near face S6 of element 247 of instance STRIP in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 102 and 575 of instance MOULD may be on the same side
  of a surface near face S6 of element 247 of instance STRIP but still crossed
  the surface in the configuration after the initial overclosure procedure.


  Adjacent slave nodes 101 and 575 of instance MOULD may be on opposite sides
  of a surface near face S6 of element 241 of instance STRIP in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 101 and 594 of instance MOULD may be on the same side
  of a surface near face S6 of element 235 of instance STRIP but still crossed
  the surface in the configuration after the initial overclosure procedure.


  Adjacent slave nodes 100 and 594 of instance MOULD may be on opposite sides
  of a surface near face S6 of element 229 of instance STRIP in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 100 and 613 of instance MOULD may be on the same side
  of a surface near face S6 of element 229 of instance STRIP but still crossed
  the surface in the configuration after the initial overclosure procedure.


  Adjacent slave nodes 99 and 613 of instance MOULD may be on opposite sides
  of a surface near face S6 of element 223 of instance STRIP in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 99 and 632 of instance MOULD may be on the same side of
  a surface near face S6 of element 217 of instance STRIP but still crossed
  the surface in the configuration after the initial overclosure procedure.


  Adjacent slave nodes 98 and 632 of instance MOULD may be on opposite sides
  of a surface near face S6 of element 211 of instance STRIP in the
  configuration after the initial overclosure procedure.


**********************************
*  Message file output, cpu #9   *
**********************************

-------------------------------------------------------------------------------

  INFORMATION REGARDING INITIAL CONTACT OVERCLOSURES FOR NEWLY DEFINED GENERAL
  CONTACT INTERACTIONS IN STEP 1

-------------------------------------------------------------------------------

  Adjacent slave nodes 654 and 655 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 210 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 654 and 674 of instance MOULD may be on the same side
  of a surface near face S4 of element 204 of instance STRIP but still crossed
  the surface in the configuration before the initial overclosure procedure.


  Adjacent slave nodes 673 and 674 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 198 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 673 and 693 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 198 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 692 and 693 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 192 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 692 and 712 of instance MOULD may be on the same side
  of a surface near face S4 of element 186 of instance STRIP but still crossed
  the surface in the configuration before the initial overclosure procedure.


  Adjacent slave nodes 711 and 712 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 186 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 711 and 731 of instance MOULD may be on the same side
  of a surface near face S4 of element 180 of instance STRIP but still crossed
  the surface in the configuration before the initial overclosure procedure.


  Adjacent slave nodes 730 and 731 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 174 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 730 and 750 of instance MOULD may be on the same side
  of a surface near face S4 of element 168 of instance STRIP but still crossed
  the surface in the configuration before the initial overclosure procedure.


  Adjacent slave nodes 749 and 750 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 168 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 749 and 769 of instance MOULD may be on the same side
  of a surface near face S4 of element 162 of instance STRIP but still crossed
  the surface in the configuration before the initial overclosure procedure.


  Adjacent slave nodes 768 and 769 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 156 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 768 and 788 of instance MOULD may be on the same side
  of a surface near face S4 of element 150 of instance STRIP but still crossed
  the surface in the configuration before the initial overclosure procedure.


  Adjacent slave nodes 787 and 788 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 150 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 787 and 807 of instance MOULD may be on the same side
  of a surface near face S4 of element 144 of instance STRIP but still crossed
  the surface in the configuration before the initial overclosure procedure.


  Adjacent slave nodes 806 and 807 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 144 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 806 and 826 of instance MOULD may be on the same side
  of a surface near face S4 of element 132 of instance STRIP but still crossed
  the surface in the configuration before the initial overclosure procedure.


  Adjacent slave nodes 825 and 826 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 132 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 825 and 845 of instance MOULD may be on the same side
  of a surface near face S4 of element 126 of instance STRIP but still crossed
  the surface in the configuration before the initial overclosure procedure.


  Adjacent slave nodes 844 and 845 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 126 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 844 and 864 of instance MOULD may be on the same side
  of a surface near face S4 of element 114 of instance STRIP but still crossed
  the surface in the configuration before the initial overclosure procedure.


  Adjacent slave nodes 863 and 864 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 114 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 654 and 655 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 210 of instance STRIP in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 654 and 674 of instance MOULD may be on the same side
  of a surface near face S4 of element 204 of instance STRIP but still crossed
  the surface in the configuration after the initial overclosure procedure.


  Adjacent slave nodes 673 and 674 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 198 of instance STRIP in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 673 and 693 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 198 of instance STRIP in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 692 and 693 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 192 of instance STRIP in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 692 and 712 of instance MOULD may be on the same side
  of a surface near face S4 of element 186 of instance STRIP but still crossed
  the surface in the configuration after the initial overclosure procedure.


  Adjacent slave nodes 711 and 712 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 186 of instance STRIP in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 711 and 731 of instance MOULD may be on the same side
  of a surface near face S4 of element 180 of instance STRIP but still crossed
  the surface in the configuration after the initial overclosure procedure.


  Adjacent slave nodes 730 and 731 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 174 of instance STRIP in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 730 and 750 of instance MOULD may be on the same side
  of a surface near face S4 of element 168 of instance STRIP but still crossed
  the surface in the configuration after the initial overclosure procedure.


  Adjacent slave nodes 749 and 750 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 168 of instance STRIP in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 749 and 769 of instance MOULD may be on the same side
  of a surface near face S4 of element 162 of instance STRIP but still crossed
  the surface in the configuration after the initial overclosure procedure.


  Adjacent slave nodes 768 and 769 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 156 of instance STRIP in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 768 and 788 of instance MOULD may be on the same side
  of a surface near face S4 of element 150 of instance STRIP but still crossed
  the surface in the configuration after the initial overclosure procedure.


  Adjacent slave nodes 787 and 788 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 150 of instance STRIP in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 787 and 807 of instance MOULD may be on the same side
  of a surface near face S4 of element 144 of instance STRIP but still crossed
  the surface in the configuration after the initial overclosure procedure.


  Adjacent slave nodes 806 and 807 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 144 of instance STRIP in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 806 and 826 of instance MOULD may be on the same side
  of a surface near face S4 of element 132 of instance STRIP but still crossed
  the surface in the configuration after the initial overclosure procedure.


  Adjacent slave nodes 825 and 826 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 132 of instance STRIP in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 825 and 845 of instance MOULD may be on the same side
  of a surface near face S4 of element 126 of instance STRIP but still crossed
  the surface in the configuration after the initial overclosure procedure.


  Adjacent slave nodes 844 and 845 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 126 of instance STRIP in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 844 and 864 of instance MOULD may be on the same side
  of a surface near face S4 of element 114 of instance STRIP but still crossed
  the surface in the configuration after the initial overclosure procedure.


  Adjacent slave nodes 863 and 864 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 114 of instance STRIP in the
  configuration after the initial overclosure procedure.


**********************************
*  Message file output, cpu #10  *
**********************************

-------------------------------------------------------------------------------

  INFORMATION REGARDING INITIAL CONTACT OVERCLOSURES FOR NEWLY DEFINED GENERAL
  CONTACT INTERACTIONS IN STEP 1

-------------------------------------------------------------------------------

**********************************
*  Message file output, cpu #11  *
**********************************

-------------------------------------------------------------------------------

  INFORMATION REGARDING INITIAL CONTACT OVERCLOSURES FOR NEWLY DEFINED GENERAL
  CONTACT INTERACTIONS IN STEP 1

-------------------------------------------------------------------------------

  Adjacent slave nodes 97 and 651 of instance MOULD may be on opposite sides
  of a surface near face S6 of element 205 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 97 and 670 of instance MOULD may be on opposite sides
  of a surface near face S6 of element 199 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 96 and 670 of instance MOULD may be on opposite sides
  of a surface near face S6 of element 199 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 96 and 689 of instance MOULD may be on the same side of
  a surface near face S6 of element 193 of instance STRIP but still crossed
  the surface in the configuration before the initial overclosure procedure.


  Adjacent slave nodes 95 and 689 of instance MOULD may be on opposite sides
  of a surface near face S6 of element 187 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 95 and 708 of instance MOULD may be on the same side of
  a surface near face S6 of element 187 of instance STRIP but still crossed
  the surface in the configuration before the initial overclosure procedure.


  Adjacent slave nodes 94 and 708 of instance MOULD may be on opposite sides
  of a surface near face S6 of element 181 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 94 and 727 of instance MOULD may be on the same side of
  a surface near face S6 of element 175 of instance STRIP but still crossed
  the surface in the configuration before the initial overclosure procedure.


  Adjacent slave nodes 93 and 727 of instance MOULD may be on opposite sides
  of a surface near face S6 of element 169 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 93 and 746 of instance MOULD may be on the same side of
  a surface near face S6 of element 169 of instance STRIP but still crossed
  the surface in the configuration before the initial overclosure procedure.


  Adjacent slave nodes 92 and 746 of instance MOULD may be on opposite sides
  of a surface near face S6 of element 163 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 97 and 651 of instance MOULD may be on opposite sides
  of a surface near face S6 of element 205 of instance STRIP in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 97 and 670 of instance MOULD may be on opposite sides
  of a surface near face S6 of element 199 of instance STRIP in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 96 and 670 of instance MOULD may be on opposite sides
  of a surface near face S6 of element 199 of instance STRIP in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 96 and 689 of instance MOULD may be on the same side of
  a surface near face S6 of element 193 of instance STRIP but still crossed
  the surface in the configuration after the initial overclosure procedure.


  Adjacent slave nodes 95 and 689 of instance MOULD may be on opposite sides
  of a surface near face S6 of element 187 of instance STRIP in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 95 and 708 of instance MOULD may be on the same side of
  a surface near face S6 of element 187 of instance STRIP but still crossed
  the surface in the configuration after the initial overclosure procedure.


  Adjacent slave nodes 94 and 708 of instance MOULD may be on opposite sides
  of a surface near face S6 of element 181 of instance STRIP in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 94 and 727 of instance MOULD may be on the same side of
  a surface near face S6 of element 175 of instance STRIP but still crossed
  the surface in the configuration after the initial overclosure procedure.


  Adjacent slave nodes 93 and 727 of instance MOULD may be on opposite sides
  of a surface near face S6 of element 169 of instance STRIP in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 93 and 746 of instance MOULD may be on the same side of
  a surface near face S6 of element 169 of instance STRIP but still crossed
  the surface in the configuration after the initial overclosure procedure.


  Adjacent slave nodes 92 and 746 of instance MOULD may be on opposite sides
  of a surface near face S6 of element 163 of instance STRIP in the
  configuration after the initial overclosure procedure.


**********************************
*  Message file output, cpu #12  *
**********************************

-------------------------------------------------------------------------------

  INFORMATION REGARDING INITIAL CONTACT OVERCLOSURES FOR NEWLY DEFINED GENERAL
  CONTACT INTERACTIONS IN STEP 1

-------------------------------------------------------------------------------

  Adjacent slave nodes 91 and 765 of instance MOULD may be on opposite sides
  of a surface near face S6 of element 157 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 91 and 784 of instance MOULD may be on the same side of
  a surface near face S6 of element 151 of instance STRIP but still crossed
  the surface in the configuration before the initial overclosure procedure.


  Adjacent slave nodes 90 and 784 of instance MOULD may be on opposite sides
  of a surface near face S6 of element 145 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 90 and 803 of instance MOULD may be on opposite sides
  of a surface near face S6 of element 139 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 89 and 803 of instance MOULD may be on opposite sides
  of a surface near face S6 of element 139 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 89 and 822 of instance MOULD may be on the same side of
  a surface near face S6 of element 133 of instance STRIP but still crossed
  the surface in the configuration before the initial overclosure procedure.


  Adjacent slave nodes 88 and 822 of instance MOULD may be on opposite sides
  of a surface near face S6 of element 127 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 88 and 841 of instance MOULD may be on opposite sides
  of a surface near face S6 of element 121 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 87 and 841 of instance MOULD may be on opposite sides
  of a surface near face S6 of element 121 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 87 and 860 of instance MOULD may be on opposite sides
  of a surface near face S6 of element 115 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 86 and 860 of instance MOULD may be on opposite sides
  of a surface near face S6 of element 115 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 91 and 765 of instance MOULD may be on opposite sides
  of a surface near face S6 of element 157 of instance STRIP in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 91 and 784 of instance MOULD may be on the same side of
  a surface near face S6 of element 151 of instance STRIP but still crossed
  the surface in the configuration after the initial overclosure procedure.


  Adjacent slave nodes 90 and 784 of instance MOULD may be on opposite sides
  of a surface near face S6 of element 145 of instance STRIP in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 90 and 803 of instance MOULD may be on opposite sides
  of a surface near face S6 of element 139 of instance STRIP in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 89 and 803 of instance MOULD may be on opposite sides
  of a surface near face S6 of element 139 of instance STRIP in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 89 and 822 of instance MOULD may be on the same side of
  a surface near face S6 of element 133 of instance STRIP but still crossed
  the surface in the configuration after the initial overclosure procedure.


  Adjacent slave nodes 88 and 822 of instance MOULD may be on opposite sides
  of a surface near face S6 of element 127 of instance STRIP in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 88 and 841 of instance MOULD may be on opposite sides
  of a surface near face S6 of element 121 of instance STRIP in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 87 and 841 of instance MOULD may be on opposite sides
  of a surface near face S6 of element 121 of instance STRIP in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 87 and 860 of instance MOULD may be on opposite sides
  of a surface near face S6 of element 115 of instance STRIP in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 86 and 860 of instance MOULD may be on opposite sides
  of a surface near face S6 of element 115 of instance STRIP in the
  configuration after the initial overclosure procedure.


**********************************
*  Message file output, cpu #13  *
**********************************

-------------------------------------------------------------------------------

  INFORMATION REGARDING INITIAL CONTACT OVERCLOSURES FOR NEWLY DEFINED GENERAL
  CONTACT INTERACTIONS IN STEP 1

-------------------------------------------------------------------------------

  Adjacent slave nodes 882 and 883 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 108 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 883 and 902 of instance MOULD may be on the same side
  of a surface near face S4 of element 108 of instance STRIP but still crossed
  the surface in the configuration before the initial overclosure procedure.


  Adjacent slave nodes 902 and 903 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 102 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 78 and 79 of instance MOULD may be on opposite sides of
  a surface near face S4 of element 90 of instance STRIP in the configuration
  before the initial overclosure procedure.


  Adjacent slave nodes 78 and 902 of instance MOULD may be on the same side of
  a surface near face S4 of element 96 of instance STRIP but still crossed the
  surface in the configuration before the initial overclosure procedure.


  Adjacent slave nodes 882 and 883 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 108 of instance STRIP in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 883 and 902 of instance MOULD may be on the same side
  of a surface near face S4 of element 108 of instance STRIP but still crossed
  the surface in the configuration after the initial overclosure procedure.


  Adjacent slave nodes 902 and 903 of instance MOULD may be on opposite sides
  of a surface near face S4 of element 102 of instance STRIP in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 78 and 79 of instance MOULD may be on opposite sides of
  a surface near face S4 of element 90 of instance STRIP in the configuration
  after the initial overclosure procedure.


  Adjacent slave nodes 78 and 902 of instance MOULD may be on the same side of
  a surface near face S4 of element 96 of instance STRIP but still crossed the
  surface in the configuration after the initial overclosure procedure.


**********************************
*  Message file output, cpu #14  *
**********************************

-------------------------------------------------------------------------------

  INFORMATION REGARDING INITIAL CONTACT OVERCLOSURES FOR NEWLY DEFINED GENERAL
  CONTACT INTERACTIONS IN STEP 1

-------------------------------------------------------------------------------

  Adjacent slave nodes 879 and 898 of instance MOULD may be on opposite sides
  of a surface near face S6 of element 103 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 85 and 879 of instance MOULD may be on opposite sides
  of a surface near face S6 of element 103 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 898 and 899 of instance MOULD may be on opposite sides
  of a surface near face S6 of element 97 of instance STRIP in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 82 and 83 of instance MOULD may be on opposite sides of
  a surface near face S6 of element 85 of instance STRIP in the configuration
  before the initial overclosure procedure.


  Adjacent slave nodes 82 and 898 of instance MOULD may be on the same side of
  a surface near face S6 of element 97 of instance STRIP but still crossed the
  surface in the configuration before the initial overclosure procedure.


  Adjacent slave nodes 879 and 898 of instance MOULD may be on opposite sides
  of a surface near face S6 of element 103 of instance STRIP in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 85 and 879 of instance MOULD may be on opposite sides
  of a surface near face S6 of element 103 of instance STRIP in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 898 and 899 of instance MOULD may be on opposite sides
  of a surface near face S6 of element 97 of instance STRIP in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 82 and 83 of instance MOULD may be on opposite sides of
  a surface near face S6 of element 85 of instance STRIP in the configuration
  after the initial overclosure procedure.


  Adjacent slave nodes 82 and 898 of instance MOULD may be on the same side of
  a surface near face S6 of element 97 of instance STRIP but still crossed the
  surface in the configuration after the initial overclosure procedure.


**********************************
*  Message file output, cpu #15  *
**********************************

-------------------------------------------------------------------------------

  INFORMATION REGARDING INITIAL CONTACT OVERCLOSURES FOR NEWLY DEFINED GENERAL
  CONTACT INTERACTIONS IN STEP 1

-------------------------------------------------------------------------------

**********************************
*  Message file output, cpu #16  *
**********************************

-------------------------------------------------------------------------------

  INFORMATION REGARDING INITIAL CONTACT OVERCLOSURES FOR NEWLY DEFINED GENERAL
  CONTACT INTERACTIONS IN STEP 1

-------------------------------------------------------------------------------

***WARNING: *CONNECTOR MOTION, TYPE=DISPLACEMENT has been prescribed with a
            jump of 3.90341E-02 in component 4 at the beginning of step 3 for
            connector with nodes  ********** and 75.

